### ISSUE TITLE
error running  task distZip

### ISSUE THREAD

**Issue by jarro** [doches/generator-dropwizard-gradle#1]
Installation went smooth.  
But got this same error on both windows and linux

Could not determine the dependencies of task ':awesome-distribution:distZip'.
Task with path ':awesome-app:gulp_publish' not found in project ':awesome-distribution'.

**Comment by doches** [comment]
Yep! Looks like I forgot to remove some front-end bits and bobs when I extracted this from my last project. Update to 0.1.1 (just published) and generate again; you should be good to go now!
